listener 1883 0.0.0.0
allow_anonymous false

# Password file — dibuat otomatis oleh start_susemon.bat
password_file mosquitto_config/passwd

# Keepalive
max_keepalive 120

# Log
log_type error
log_type warning
log_type notice
log_type information
