name: susemon_flutter
description: "SUSEMON - Suhu dan Kelembapan Server Monitoring (PBL-TRPL412)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.0
  google_fonts: ^6.2.1
  # HTTP & WebSocket
  http: ^1.2.1
  web_socket_channel: ^3.0.1
  # State management
  provider: ^6.1.2
  # Local storage
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  # Date formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
